### ISSUE TITLE
iOS 8 Issues

### ISSUE THREAD

**Issue by karks88** [shankariyerr/griddd#3]
When using griddd on iOS 8 devices via BrowserStack, I'm seeing that some columns aren't displaying properly.

If you take a look at the attached image, you'll see a correct display on the left - iOS 9 (iPhone 6s)
On the right, the text containers aren't showing - iOS8 (iPhone 6 Plus)

![ios-griddd](https://user-images.githubusercontent.com/3975843/28642925-0efd94a0-7222-11e7-9ee8-ab530bd794a0.jpg)

Not sure if this is just a bug with BrowserStack or something in the responsive code. Haven't noticed it on Android at all.

Also found the same issue further down the same page. Just for your reference, the URL is http://karks2015.pairserver.com/hfamadvocacy/

**Comment by shankara-subramani** [comment]
@karks88 let me look into it.

**Comment by karks88** [comment]
Thanks!

**Comment by karks88** [comment]
Just to follow up on this, I think I may have found the issue. On iOS 8 and below:
`-webkit-box-orient:horizontal;`

Should be changed to:
`-webkit-box-orient:vertical;`

That seems to have fixed it in my testing.

**Comment by shankara-subramani** [comment]
@karks88 I have implemented your suggestion which should fix the issue. 
Thanks for narrowing down the problem. 🙌

**Comment by karks88** [comment]
My pleasure!
